[build]
  command = "npm run generate"
  publish = "dist"

# Configuración para formularios
[build.environment]
  NODE_VERSION = "18"

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Configuración específica para el formulario de contacto
[[headers]]
  for = "/contact-success.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Redirects para el formulario
[[redirects]]
  from = "/contact-success"
  to = "/contact-success.html"
  status = 200

# Configuración de formularios de Netlify
[forms]
  # Configuración global para todos los formularios
  [forms.settings]
    # Habilitar notificaciones por email
    email = true
    # Habilitar protección contra spam
    spam_protection = true

# Configuración específica del formulario de contacto
[forms.settings]
  name = "contact"
  action = "/contact-success.html"
  
# Configuración de notificaciones
	[forms.notifications]
# Notificación por email al recibir un mensaje
[[forms.notifications.email]]
	to = "vake08@gmail.com"  # Cambiar por tu email
	subject = "Nuevo mensaje de contacto desde tu portfolio"
	template = """
	Has recibido un nuevo mensaje de contacto:
	
	Nombre: {{ name }}
	Email: {{ email }}
	Asunto: {{ subject }}
	
	Mensaje:
	{{ message }}
	
	---
	Información adicional:
	Fecha: {{ timestamp }}
	Navegador: {{ user-agent }}
	Página: {{ page-url }}
	"""

# Variables de entorno para diferentes contextos
[context.production.environment]
  NUXT_PUBLIC_SITE_URL = "https://valeriamanriquez.cl/"

#[context.deploy-preview.environment]
  #NUXT_PUBLIC_SITE_URL = "https://deploy-preview-$REVIEW_ID--tu-sitio.netlify.app"

#[context.branch-deploy.environment]
  #NUXT_PUBLIC_SITE_URL = "https://$BRANCH--tu-sitio.netlify.app"
