[build]
  command = "npm run generate"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Headers de seguridad
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"

# Configuración específica para el formulario de contacto
[[headers]]
  for = "/contact-success.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Redirects para el formulario
[[redirects]]
  from = "/contact-success"
  to = "/contact-success.html"
  status = 200

# Variables de entorno para diferentes contextos
[context.production.environment]
  NUXT_PUBLIC_SITE_URL = "https://tu-dominio.netlify.app"

[context.deploy-preview.environment]
  NUXT_PUBLIC_SITE_URL = "https://deploy-preview-$REVIEW_ID--tu-sitio.netlify.app"

[context.branch-deploy.environment]
  NUXT_PUBLIC_SITE_URL = "https://$BRANCH--tu-sitio.netlify.app"
